name: Deploy Plugin to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prepare gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout -B gh-pages

      - name: Clear old files
        run: git rm -rf .

      - name: Copy plugin files to root
        run: |
          cp -r plugins/sniper/* .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy sniper plugin to gh-pages"
          git push origin gh-pages --force
